energy_security:
  Foreign Dependency: 6
  Energy Imports: 4
  Reserves: 4
  Trade: 4
  Minerals Trade: 4
  Production: 6
  Energy Access: 4
  Consumption: 5
  Energy Prices: 2

economic_opportunity:
  Trade: 3
  Production: 3
  Technology Demand: 4
  Technological Readiness: 0
  Energy Prices: 3
  Investment: 3
  Energy Access: 3
  Foreign Dependency: 3
  Cost Competitiveness: 3
  Consumption: 3

psi:
  friendshore: 0.4
  opportunity: 0.4
  development: 0.2

partnership_opportunity_components:
  trade_index: 2
  econ_opp_index: 4
  energy_security_index: 1
  climate_policy_weight: 0.05

partnership_friendshore_components:
  imp_trade_index: 2
  econ_opp_raw: 0
  es_need: 3
  eo_partner: 3
  outbound_index: 2
